Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_points.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep1.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "test_rep2.py", line 24, in <module>
    from utils.utils0 import *
  File "/home/pakpoom_kh/spppt-2/utils/utils0.py", line 7, in <module>
    import scipy.ndimage as nd
ModuleNotFoundError: No module named 'scipy'
